---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: maven-app
  namespace: default
  labels:
    app: maven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
      - name: maven-app
        image: "patel244/sample-for-jenkins-0.0.2.1:latest"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: maven-app
  namespace: default
spec:
  selector:
    app: maven-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80
